- Sources/RoktUXHelper/UI/Components/Common/View+Extension.swift
- Sources/RoktUXHelper/UI/Components/ScrollableColumnComponent.swift
- Sources/RoktUXHelper/UI/Components/ScrollableRowComponent.swift
Merging back a fix we made in v4.6.1 to mitigate the "invalid frame dimension" error on ScrollableColumn into UXHelper. Setting frame `height` with value `.infinity` was triggering a "invalid frame dimension" error.
Fixes [LAYOUT=1613](https://rokt.atlassian.net/browse/LAYOUT-1613)
ScrollableColumn conditionally sets either maxHeight or height.
Tested layout with ScrollableColumn with weight no longer shows invalid frame dimension error.
> LAYOUT-1613 - Merge v4.6.1 fixes back into UXHelper

- Example/Example/SampleViewController.swift
- Sources/RoktUXHelper/UI/RoktLayoutUIView.swift
- Sources/RoktUXHelper/UI/RoktLayoutView/RoktLayoutView.swift
- Sources/RoktUXHelper/UI/RoktLayoutView/RoktLayoutViewModel.swift
- RoktLayoutView would resize when loaded from max height to its appropriate size for a brief moment
- RoktLayoutUIView has a few layout constraint warnings
- additionally, RoktLayoutUIView had an issue with not laying out accordingly due to `decideTranslatesAutoresizingMask()` enabling `translatesAutoresizingMaskIntoConstraints` for RoktLayoutUIView which creates NSAutoresizingMaskLayoutConstraints that conflicts with the constraints we set.
| View | Before | After |
|:--------:|:-----------:|:----------:| 
| RoktLayoutView | https://github.com/user-attachments/assets/3ad5ba23-dd9f-42ad-8f5d-837a2ff0cc1b | https://github.com/user-attachments/assets/2c2060ef-4b4d-44f8-a93b-156bac913898 |
| RoktLayoutUIView | ![Screenshot 2024-11-08 at 3 32 …
> NI-327 - layout constraint warnings

- Sources/RoktUXHelper/Data/Model/CustomStateMap.swift
Need to expose CustomStateMap as public so it can be re-used in the Rokt SDK view state (for caching).
Fixes NO-JIRA
Expose CustomStateMap as public
Integrated in Rokt SDK view state
> NO-JIRA - CustomStateMap public to use in cache viewstate

- Sources/RoktUXHelper/Data/Model/CustomStateMap.swift
- Sources/RoktUXHelper/Data/Model/ExperienceResponse/PageModel.swift
- Sources/RoktUXHelper/Data/Model/RoktPluginViewState.swift
- Sources/RoktUXHelper/RoktUX.swift
- Sources/RoktUXHelper/Services/LayoutState.swift
- Sources/RoktUXHelper/Services/LayoutStateRepresenting.swift
- Sources/RoktUXHelper/UI/Components/CarouselComponent.swift
- Sources/RoktUXHelper/UI/Components/Common/UIViewController+Extension.swift
- Sources/RoktUXHelper/UI/Components/GroupedDistributionComponent.swift
- Sources/RoktUXHelper/UI/Components/OneByOneComponent.swift
- Sources/RoktUXHelper/UI/Components/ViewModel/DistributionViewModel.swift
This PR lays the UXHelper foundations for part 1 of caching view states, to be used on the SDK side view states caching PR.
Fixes https://rokt.atlassian.net/browse/LAYOUT-1720
- Move RoktPluginViewState to UXHelper
- Restore view states from RoktPluginViewStates passed into loadLayout from SDK
- Introduce onPluginViewStateChange callback to capture view states updates
- LayoutState stores pluginId, initialPluginViewStates and the onPluginViewStateChange callback
- DistributionViewModels and components updated to restore from initialPluginViewStates and to capture view states on change
Tested locally (recordings in SDK-side PR)
> LAYOUT-1720 - caching view states part 1 (UXHelper)

- Sources/RoktUXHelper/RoktUX.swift
- Sources/RoktUXHelper/UI/Components/Common/UIViewController+Extension.swift
- Sources/RoktUXHelper/UI/Components/EmbeddedComponent/EmbeddedComponentViewModel.swift
There was a bug in the SignalDismissal that was not populated when user dismiss the view.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-378))]
* Ownership of eventService changed to RoktUX
* made closeModal function public
Tested locally. Will add E2E test to capture this scenario as it is hard to be Unit tested at the moment.
> NI-378 Change the ownership of eventService to RoktUX

- Sources/RoktUXHelper/Data/Model/Event/ProcessedEvent.swift
- Sources/RoktUXHelper/Data/Model/RoktPluginViewState.swift
- Sources/RoktUXHelper/RoktUX.swift
- Sources/RoktUXHelper/Services/Events/EventProcessor.swift
- Sources/RoktUXHelper/UI/Components/Common/String+Extension.swift
Adds UXHelper module changes to support caching and restoring sent events.
Fixes https://rokt.atlassian.net/browse/LAYOUT-1763
- loadLayout method updated to receive (optional) restored processedEventHashes from SDK
- EventProcessor filters out duplicate events by hash
- Updates to ProcessedEvent and 
Caching events was tested on the SDK-side
> LAYOUT-1763: Implement sent event caching on UXHelper module

- Sources/RoktUXHelper/Data/Model/Event/ProcessedEvent.swift
- Sources/RoktUXHelper/Data/Model/RoktPluginViewState.swift
- Sources/RoktUXHelper/RoktUX.swift
- Sources/RoktUXHelper/Services/Events/EventProcessor.swift
- Sources/RoktUXHelper/UI/Components/Common/String+Extension.swift
Extracting sent event handling out of uxhelper as this is not required. Sent event filtering will be moved off to SDK
Fixes NO-JIRA
Extracting sent event handling out of uxhelper. (Reverting changes related to sent event filtering from this PR https://github.com/ROKT/rokt-ux-helper-ios/pull/26
> NO-JIRA: extract sent event handling out of uxhelper

- Sources/RoktUXHelper/Services/Events/EventProcessor.swift
- Tests/RoktUXHelperTests/Services/Events/TestEventProcessor.swift
- Tests/RoktUXHelperTests/Services/Mock/MockEventProcessor.swift
Currently if RoktUX is deallocated and there are partner events in queue waiting to be published to the user, the pending events will be lost.
this is to fix the EventProcessor to finish publishing all events before deallocating itself.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-392))]
> NI-392 - retain event processor

- Sources/RoktUXHelper/Data/Model/Event/EventType.swift
- Sources/RoktUXHelper/RoktUX.swift
- Sources/RoktUXHelper/Services/Events/EventProcessor.swift
- Sources/RoktUXHelper/Services/Events/EventService.swift
- Sources/RoktUXHelper/Services/Events/EventServicing.swift
- Sources/RoktUXHelper/UI/Components/Common/UIViewController+Extension.swift
- Tests/RoktUXHelperTests/Services/Events/TestEventProcessor.swift
- Tests/RoktUXHelperTests/Services/Events/TestEventService.swift
- Tests/RoktUXHelperTests/Services/Mock/MockEventProcessor.swift
- Tests/RoktUXHelperTests/UI/Utils/MockModels.swift
RoktUX to provide a way to send partner events when instant purchase succeeds or fails.
- also cherry-picked the event processor retention change from main
Fixes [([issue](https://rokt.atlassian.net/browse/NI-392))]
> NI-385 - send catalog events

- Sources/RoktUXHelper/Data/Model/Event/EventRequest.swift
- Sources/RoktUXHelper/UI/Components/Common/View+Extension.swift
Need to change the escaping callback to optional which is escaping by default and more feature prof
Tested locally
> Change escaping callback optional which is escaping by default

- Sources/RoktUXHelper/UI/Components/WhenComponent.swift
we were noticing that the image was being fetched twice in the app, this is due to the conditional building of components in the when node. When the condition is true there are 2 conditional branches the when component takes to build the component, when it is waiting for the animation to load and when the animation is finished. these 2 branches represent 2 identities for the underlying swiftUI view, which tells the rendering engine that it's 2 separate views, thus replacing any states the view might have such as the fetched image.
fix is to reduce the conditional branches to just 1.
| before | sanity testing with expand card |
|:-------:|:-------------:|
| <img width="975" alt="Screenshot 2024-12-12 at 10 31 47 AM" src="https://github.com/user-attachments/assets/73481e29-08b4-41f1-97f8-ce9 …
> NI-411 - fix fetching image twice

- Sources/RoktUXHelper/RoktUX.swift
- Sources/RoktUXHelper/UI/Components/Common/UIViewController+Extension.swift
This PR is to align the partner event sent when a cached experience with isPluginDismissed is retrieved with Android SDK. Previously we sent PlacementReady however this case should be sending PlacementCompleted.
Fixes https://rokt.atlassian.net/browse/LAYOUT-1829
- Move isPluginDismissed check to the top of the method to ensure it is checked before any other logic is executed
- Send PlacementClosed event if isPluginDismissed
Tested locally
> LAYOUT-1829 - Fix partner event on cached experience with isPluginDismissed

- Sources/RoktUXHelper/UI/RoktLayoutUIView.swift
- Sources/RoktUXHelper/UI/RoktLayoutView/RoktLayoutViewModel.swift
This PR is to make log parity between SwiftUI and UIKit embedded views.
Tested locally
> NI-421 send same logs on swiftui and uikit embedded

- Sources/RoktUXHelper/UI/Components/OuterLayerComponent.swift
- Sources/RoktUXHelper/UI/Components/ViewModel/BasicTextViewModel.swift
- Sources/RoktUXHelper/UI/Components/ViewModel/ProgressIndicatorViewModel.swift
- Sources/RoktUXHelper/UI/Components/ViewModel/RichTextViewModel.swift
- Sources/RoktUXHelper/Utils/LazyPublished.swift
our swiftUI views are being redrawn too many times resulting in really slow loading times for more complex views.
here's a couple things i've identified that works and has cut down rendering time by half (rendering the bottomsheet shown as benchmark)
- reducing the use of constants when initializing bindings, can't find any literature on it, but this can trigger a redraw when we initialize a view that has a binding with a constant.
- @Published property triggers the view to redraw indiscriminately even if the value is same, introducing a new property wrapper @LazyPublished that only triggers redraw when the wrapped value is different (thanks to [swift evolution 0258](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0258-property-wrappers.md#referencing-the-enclosing-self-in …
> NI-394 - reduce redraw

- .github/composite_actions/run_xcodebuild_tests_swift_5/action.yml
- .github/composite_actions/run_xcodebuild_tests_swift_6/action.yml
- .github/workflows/pull-request.yml
A simple way to configure github actions to run on xcode 15 or xcode 16, with warnings and errors from linting and unit tests now showing as annotations and in files changed 
Fixes [([issue](https://rokt.atlassian.net/browse/NI-300))]
> NI-204 - add github composite actions for xcode 16

- .swiftlint.yml
- Sources/RoktUXHelper/RoktUX.swift
- Sources/RoktUXHelper/Services/Events/EventProcessor.swift
- Sources/RoktUXHelper/UI/Components/Common/UIViewController+Extension.swift
- Sources/RoktUXHelper/Utils/DebounceCollector.swift
- Tests/RoktUXHelperTests/Services/Events/TestEventProcessor.swift
- Improve EventProcessor to debounce whenever a new event is collected.
- run EventProcessor on main thread for testing (overcome slow CI)
| before | after |
|:------:|:-----:|
| <img width="724" alt="Screenshot 2025-01-20 at 4 35 34 PM" src="https://github.com/user-attachments/assets/13bc5ef6-4e4f-47b5-bf81-a9d1078ee7f6" /> | <img width="730" alt="Screenshot 2025-01-20 at 4 35 40 PM" src="https://github.com/user-attachments/assets/f327fbd6-b6a8-449f-96ca-349dc95cb6ce" /> |
Fixes [([issue](https://rokt.atlassian.net/browse/NI-448))]
> NI-448 - add DebounceCollector

- Sources/RoktUXHelper/UI/Components/Common/Image/AsyncImageView.swift
- Tests/RoktUXHelperTests/UI/Components/TestDataImageComponent.swift
There is a bug that padding or margin of the image remains in the layout if the image failed to download
Fixes [([issue](https://rokt.atlassian.net/browse/NI-503))]
* Changed the thread where the image is marked as invalid
The test added.
> Ni-503 i os failed downloaded image will not remove the margin and padding from view

- Sources/RoktUXHelper/UI/Components/ViewModel/RoktEmbeddedViewModel.swift
Because the `RoktEmbeddedViewModel` doesn't get retained in `OuterLayerComponent` on every redraw the view model gets deallocated with its contents.
When the asynchronous code in `updateAttributedStrings` runs the view model would have been deallocated and it's variables would be `nil`, thus the fix is to capture the layouts array so that it can be accessed when the code block runs.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-504))]
> NI-504 - fix color mode update

- CHANGELOG.md
- MIGRATING.md
As the class name of ImageLoader has been changed, there is a need for migration guide 
Fixes [([issue](https://rokt.atlassian.net/browse/NI-508))]
MIGRATING.md file added
> NI-508 create Migrating.md file

- CHANGELOG.md
- Sources/RoktUXHelper/UI/Components/Common/CGFloat+Extension.swift
- Sources/RoktUXHelper/UI/Components/Common/CGSize+Extension.swift
- Sources/RoktUXHelper/UI/Components/Common/View+Extension.swift
- Tests/RoktUXHelperTests/UI/Components/Common/TestCGFloatExtension.swift
- Tests/RoktUXHelperTests/UI/Components/Common/TestCGSizeExtension.swift
We are currently passing around width and height dimensions with really high decimal places, this can lead to precision issues. Lately, we have noticed artefacts such as `onEmbeddedSizeChange` being called back repeatedly as the value bounces between minute changes.
Since there's no benefit to having such high precision, we have decided to limit the view dimensions to 2 decimal places to resolve these precision issues.
| before | after |
|:-------:|:-----:|
| ![Screenshot 2025-02-14 at 10 43 46 AM](https://github.com/user-attachments/assets/c600ed02-cdf1-4fe9-af40-6e2ce1e2eba8) | ![Screenshot 2025-02-14 at 10 47 09 AM](https://github.com/user-attachments/assets/846b2bc6-e3f7-4e08-87cd-d7a3d1d1a947) |
Fixes [([issue](https://rokt.atlassian.net/browse/NI-558))]
- update `readSize` modifier …
> NI-558 - update size precision

- CHANGELOG.md
- Package.resolved
- Package.swift
- Sources/RoktUXHelper/Services/LayoutTransformer/LayoutTransformer.swift
- Sources/RoktUXHelper/Services/LayoutTransformer/StyleTransformer.swift
- Sources/RoktUXHelper/UI/Components/DataImageCarouselComponent.swift
- Sources/RoktUXHelper/UI/Components/LayoutSchemaComponent.swift
- Sources/RoktUXHelper/UI/Components/ViewModel/DataImageCarouselViewModel.swift
- Sources/RoktUXHelper/UI/Components/ViewModel/LayoutSchemaViewModel.swift
- Tests/RoktUXHelperTests/Data/Model/ModelTestData.swift
- Tests/RoktUXHelperTests/Services/LayoutTransformer/TestStyleTransformer.swift
- Tests/RoktUXHelperTests/Supporting Files/DataImageCarousel/node_data_image_carousel.json
- Tests/RoktUXHelperTests/UI/Components/TestImageCarouselComponent.swift
Need to consume the DCUI 2.2.0-alpha2 with new node DataImageCarousel
Fixes [([issue](https://rokt.atlassian.net/browse/NI-570))]
* DCUI schema updated
* LayoutTransformer updated to support the new node
* StyleTransformer update to support new styles
* Empty DataImageCarousel created
Unit test added.
> Ni 570 i os consume data image carousel dcui alpha version

- CHANGELOG.md
- Package.resolved
- Package.swift
- Sources/RoktUXHelper/Data/Model/Event/RoktUXEvent.swift
- Sources/RoktUXHelper/Data/Model/ExperienceResponse/RoktUXOpenURLType.swift
- Sources/RoktUXHelper/RoktUX.swift
- Sources/RoktUXHelper/Services/Events/EventService.swift
- Sources/RoktUXHelper/Services/UXEventsDelegate.swift
- Tests/RoktUXHelperTests/Services/Events/TestEventService.swift
Add `Passthrough` support in `OpenLinks`
Fixes [LAYOUT-2195](https://rokt.atlassian.net/browse/LAYOUT-2195)
* Update schema version to "2.2.0-alpha3"
* Added Passthrough as an option to the OpenLinks and RoktUXOpenURLType.
* Update `OpenUrl` UXEvent to include `layoutId`
* Add unit tests
Added unit tests
The PR target is `workstation/dataImageCarousel` as the schema version is dependent on that
> LAYOUT-2195 - Implement URL Passthrough option for OpenLinks

- CHANGELOG.md
- Sources/RoktUXHelper/UI/Components/CarouselComponent.swift
- Sources/RoktUXHelper/UI/Components/GroupedDistributionComponent.swift
- Sources/RoktUXHelper/UI/Components/OneByOneComponent.swift
- Sources/RoktUXHelper/UI/Components/Style/StyleComponent.swift
Implement user interaction as a proxy for SignalViewed to track user engagement with offer components.
Fixes [LAYOUT-2267](https://rokt.atlassian.net/browse/LAYOUT-2267)
Add modifiers to offer components and trigger signal viewed
Tested locally with logs added.
> LAYOUT-2267 - Add user interaction as a proxy for SignalViewed

- Sources/RoktUXHelper/UI/Components/WhenComponent.swift
I am not able to read binded state updates such as items["currentProgress"] unless it is attached to a swiftUI view, so I have to revert WhenComponent's implementation to use the view's state variables rather than accessing it directly from the LayoutState items dictionary.
> fix when component

- Sources/RoktUXHelper/UI/Components/DataImageCarouselComponent.swift
- Sources/RoktUXHelper/UI/Components/ViewModel/DataImageCarouselViewModel.swift
- add an additional check for images corresponding to the color scheme of the app.
- only show indicator if image is loaded.
| before | after |
|:------:|:------:|
| ![Simulator Screenshot - iPhone 16 Pro - 2025-04-01 at 14 19 57](https://github.com/user-attachments/assets/e0cf017b-36cf-4555-87c0-7a7a7810754a) | ![Simulator Screenshot - iPhone 15 Pro - 2025-04-01 at 14 20 00](https://github.com/user-attachments/assets/e5c4c900-68b0-4985-b695-f72b0716c7e9) |
> fix hide indicator if no images in dark mode

- Sources/RoktUXHelper/UI/Components/RowComponent.swift
- Sources/RoktUXHelper/UI/Components/WhenComponent.swift
since we are injecting the View Models from the parent we should use ObservedObject.
> fix rowComponent to use ObservedObject

- Sources/RoktUXHelper/Data/Model/ExperienceResponse/RoktUXEventData.swift
- Sources/RoktUXHelper/Data/Model/ExperienceResponse/RoktUXExperienceResponse.swift
- Sources/RoktUXHelper/Data/Model/ExperienceResponse/RoktUXPageModel.swift
- Sources/RoktUXHelper/Data/Model/ExperienceResponse/RoktUXPlacementResponse.swift
- Sources/RoktUXHelper/Data/Model/ExperienceResponse/RoktUXRealTimeEvent.swift
- Sources/RoktUXHelper/Data/Model/ExperienceResponse/RoktUXS2SExperienceResponse.swift
- Sources/RoktUXHelper/Services/Events/EventProcessor.swift
- Tests/RoktUXHelperTests/Services/Events/TestEventProcessor.swift
- Consume event data from api 
- more tests to TestEventProcessor
Fixes [([issue](https://rokt.atlassian.net/browse/NI-552))]
- add RoktUXRealTimeEvent and RoktUXEventData
> NI-552 - consume event data from api

- CHANGELOG.md
- Sources/RoktUXHelper/Data/Model/Constants.swift
- Sources/RoktUXHelper/UI/Components/Common/View+Extension.swift
The isVisible state was getting cached and the timer was considering old value when sending the status to the callback.
Fixes [SQDSDKS-7461](https://mparticle-eng.atlassian.net/browse/SQDSDKS-7461)
- Extracted the logic into `BecomingViewedModifier` and reuse the handling
- 
Tested locally
https://github.com/user-attachments/assets/a75eed3d-307f-4df6-8883-9581393e0c4f
> fix: SignalViewed trigger when initial reported state is different

- .github/composite_actions/run_xcodebuild_tests/action.yml
- CHANGELOG.md
- Sources/RoktUXHelper/UI/Components/Distribution/CarouselDistributionComponent.swift
- Tests/RoktUXHelperTests/UI/Components/Distribution/TestCarouselDistributionComponent.swift
The `CarouselDistribution` was missing the styling capability of it's own. The styles applied to the carousel was getting transferred to the pages and not to the container itself.
- Apply the styles to `HStack` container hosting the pages.
- Change the max height updation logic to add margin and padding
Tested locally with mock JSON
https://github.com/user-attachments/assets/46d4268d-8b16-4c7d-b725-989ff05f1ad2
> feat: implement the carousel and page styling

- CHANGELOG.md
- Sources/RoktUXHelper/UI/Components/ViewModel/PredicateHandling.swift
- Tests/RoktUXHelperTests/UI/ViewModel/TestWhenViewModel.swift
The `Progression` predicates in `When` component are not handling negative values as it is implemented in the `Position` predicate.
```json
{
"type": "When",
"node": {
"predicates": [
{
"type": "Progression",
"predicate": { "condition": "is-not", "value": "-1" }
}
],
"children": []
}
}
```
The above component should evaluate true for all offer position except for the last one.
Fixes [SDKE-100](https://rokt.atlassian.net/browse/SDKE-100)
- Updated PredicateHandling to correctly calculate progression for negative predicate values.
- Added unit tests to validate behaviour for negative progression conditions (is, isAbove, isBelow).
Tested locally with mock JSON
https://github.com/user-attachments/assets/6c72fac1-8a40-435a-824e-de0e5d767a5e
Add any notes or extra information here that might be …
> fix: Add support for negative values in progression predicate

- .github/dependabot.yml
Adds config for dependabot for Swift
> chore: Configure dependabot for Swift

- .github/composite_actions/run_xcodebuild_tests/action.yml
- .github/workflows/release-from-main.yml
- Gemfile
- Gemfile.lock
- Changed the Xcode version from 15.4 to 16.4.0
- Removed the `use-swift-5` input parameter as it is no longer needed.
- Updated the test command to reflect the new Xcode version and simulator settings.
> fix: Update Xcode version in CI workflow

- Sources/RoktUXHelper/UI/Components/Common/CGRect+Extension.swift
- Sources/RoktUXHelper/UI/Components/Common/View+Extension.swift
- Tests/RoktUXHelperTests/UI/Components/Common/TestCGRectExtension.swift
- codecov.yml
Timer closures can execute on different threads than the UI thread where SwiftUI views run. Swift 6 requires captured values to be Sendable so we're capturing size and frame outside of the timer context which are both sendable
handleVisibilityChange
- Breakpoints on distributions using onBecomingViewed
N/A
> fix: Do not capture GeometryProxy in Timer
