ROKT/rokt-ux-helper-ios

Sources/RoktUXHelper/Data/Model/Constants.swift
Sources/RoktUXHelper/Services/Events/EventService.swift
Tests/RoktUXHelperTests/UI/Utils/TestEventDateFormatter.swift

fix date formatter from 12 hour to 24 hour format
Describe the tests that you ran to verify your changes. 

fix DateFormatter

---

Package.resolved
Package.swift
Sources/RoktUXHelper/Data/Model/ExperienceResponse/SlotModel.swift
Sources/RoktUXHelper/Data/Model/RoktIntegrationInfoDetails.swift
Sources/RoktUXHelper/Services/LayoutTransformer/LayoutTransformer.swift
Sources/RoktUXHelper/UI/Components/CatalogResponseButtonComponent.swift
Sources/RoktUXHelper/UI/Components/CatalogStackedCollectionComponent.swift
Sources/RoktUXHelper/UI/Components/LayoutSchemaComponent.swift
Sources/RoktUXHelper/UI/Components/ViewModel/CatalogResponseButtonViewModel.swift
Sources/RoktUXHelper/UI/Components/ViewModel/CatalogStackedCollectionViewModel.swift
Sources/RoktUXHelper/UI/Components/ViewModel/LayoutSchemaViewModel.swift

- basic CatalogStackedCollection and CatalogResponseButton node
- consume 2.2.0-alpha1 DcuiSchema
[sample json to render](https://gist.github.com/WeiYewT/a33f69ff4c0e9164cc6ad3b18743c9fa)
follow up PR to add data binding to catalogItems
Fixes [([issue](https://rokt.atlassian.net/browse/NI-340))]
Describe the tests that you ran to verify your changes. 

NI-340 - render catalog items

---

Sources/RoktUXHelper/Data/Model/CustomStateMap.swift
Sources/RoktUXHelper/Data/Model/ExperienceResponse/ExperienceResponse.swift
Sources/RoktUXHelper/Data/Model/ExperienceResponse/PageModel.swift

Need to make pageModel public to re-use in SDK execute().
Fixes NO-JIRA
Make pageModel (and its necessary properties) public
Tested using pageModel in SDK execute() method

NO-JIRA - make pagemodel public

---

Sources/RoktUXHelper/Data/Model/Constants.swift
Sources/RoktUXHelper/Services/Events/EventProcessor.swift

Move event buffer duration closer to implementation and adjust duration to match Android and web
- Move constant
N/A
N/A

NOJIRA - Move event buffer duration closer to implementation

---

Example/Example.xcodeproj/project.pbxproj
Example/Example.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Sources/RoktUXHelper/Data/Model/Constants.swift
Sources/RoktUXHelper/Data/Model/CustomStateMap.swift
Sources/RoktUXHelper/Data/Model/Event/EventRequest.swift
Sources/RoktUXHelper/Data/Model/Event/EventsPayload.swift
Sources/RoktUXHelper/Data/Model/Event/ProcessedEvent.swift
Sources/RoktUXHelper/Data/Model/Event/RoktEventNameValue.swift
Sources/RoktUXHelper/Data/Model/ExperienceResponse/ExperienceResponse.swift
Sources/RoktUXHelper/Data/Model/ExperienceResponse/PageModel.swift
Sources/RoktUXHelper/RoktUX.swift
Sources/RoktUXHelper/Services/DiagnosticServicing.swift
Sources/RoktUXHelper/Services/Events/EventProcessor.swift
Sources/RoktUXHelper/Services/Events/EventService.swift
Tests/RoktUXHelperTests/Services/Events/TestEventProcessor.swift
Tests/RoktUXHelperTests/Services/Events/TestEventService.swift
Tests/RoktUXHelperTests/Services/Mock/MockEventProcessor.swift
Tests/RoktUXHelperTests/Services/TestEventRequest.swift
Tests/RoktUXHelperTests/UI/Components/TestOneByOneComponent.swift
Tests/RoktUXHelperTests/UI/Utils/MockModels.swift
Tests/RoktUXHelperTests/UI/Utils/TestPlaceHolder.swift
Tests/RoktUXHelperTests/UI/ViewModel/TestCreativeResponseViewModel.swift
Tests/RoktUXHelperTests/UI/ViewModel/TestDistributionViewModel.swift
Tests/RoktUXHelperTests/UI/ViewModel/TestRoktEmbeddedViewModel.swift

Need to update catalog-item workstation branch from main to have the latest changes regarding the events
Separate it in a separate PR to make the PR review process simpler

No jira update catalog item workstation branch from main

---

.gitignore
.swiftpm/xcode/package.xcworkspace/xcshareddata/IDETemplateMacros.plist

Add the standard Rokt header with licence to shared data
File header
N/A
N/A

No jira - Add template for FILEHEADER

---

.github/pull_request_template.md

Remove unused checkboxes from PR template
Fixes N/A
- PR template
N/A
N/A

NOJIRA - Remove unused checkboxes from PR template

---

Sources/RoktUXHelper/RoktUX.swift
Sources/RoktUXHelper/UI/Components/Config/RoktUXConfig.swift
Sources/RoktUXHelper/UI/Components/EmbeddedComponent/EmbeddedComponentViewModel.swift
Sources/RoktUXHelper/UI/Components/ViewModel/RoktEmbeddedViewModel.swift
Sources/RoktUXHelper/UI/RoktLayoutUIView.swift
Sources/RoktUXHelper/UI/RoktLayoutView/RoktLayoutViewModel.swift

Need to support minimum debug logs to help integration trubleshooting. 
Fixes [([issue](https://rokt.atlassian.net/browse/NI-405))]
* New UXConfig introduced
* Print debug logs when the feature is enabled
Tested with Example app
https://github.com/user-attachments/assets/03df62c6-153e-4659-9378-341628f5ead6

NI-405 support debug logs

---

Sources/RoktUXHelper/RoktUX.swift

remove strong retention of layoutState

remove retaining layoutstate

---

.github/workflows/pipeline.yml
.github/workflows/pull-request.yml
.github/workflows/swiftlint.yml
.gitignore
Sources/RoktUXHelper/Data/Model/RoktPluginViewState.swift
Sources/RoktUXHelper/RoktUX.swift
Sources/RoktUXHelper/Services/Events/EventProcessor.swift
Sources/RoktUXHelper/Services/LayoutState.swift
Sources/RoktUXHelper/UI/Components/Common/UIViewController+Extension.swift
Sources/RoktUXHelper/UI/Components/Config/RoktUXConfig.swift
Sources/RoktUXHelper/UI/Components/GroupedDistributionComponent.swift
Sources/RoktUXHelper/Utils/LazyPublished.swift
Tests/RoktUXHelperTests/Services/Events/TestEventProcessor.swift

Create github actions

---

.github/dependabot.yml

Adding dependabot to ensure Github actions is always up to date
Fixes N/A
- Add dependabot
N/A
N/A

NOJIRA - Create dependabot.yml

---

Sources/RoktUXHelper/Services/LayoutState.swift
Sources/RoktUXHelper/Services/LayoutStateRepresenting.swift
Sources/RoktUXHelper/UI/Components/ViewModel/BasicTextViewModel.swift
Sources/RoktUXHelper/UI/Components/ViewModel/ProgressIndicatorViewModel.swift
Sources/RoktUXHelper/UI/Components/ViewModel/RichTextViewModel.swift
Tests/RoktUXHelperTests/Services/TestLayoutState.swift

- update BasicTextViewModel and ProgressIndicatorViewModel when the current offer and viewable items bindings are set.
| before | after |
|:-------:|:-----:|
| https://github.com/user-attachments/assets/e4efe616-9c2d-4d9e-9c76-f95dd9a03d8c | https://github.com/user-attachments/assets/ad1baeed-91b9-405e-a0a9-f5737582b57e |
Fixes [([issue](https://rokt.atlassian.net/browse/NI-492))]

NI-492 - fix progress indicator

---

Example/Example.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Example/Example/SampleViewController.swift
Example/Example/SampleViewModel.swift
Tests/RoktUXHelperTests/Services/TestLayoutState.swift

This PR is to fix the build failure on the main branch, and update the Example application with latest changes.
Tests pass and Example application updated with latest ImageLoader changes.

No-jira fix build failure for new tests

---

Sources/RoktUXHelper/Services/Events/EventProcessor.swift
Tests/RoktUXHelperTests/Services/Events/TestEventProcessor.swift

reverting debouncing logic for further testing on other platforms like ReactNative.

revert debouncing logic

---

Sources/RoktUXHelper/Data/Model/Styles/BaseStyles.swift
Sources/RoktUXHelper/Services/LayoutTransformer/LayoutTransformer.swift
Sources/RoktUXHelper/Services/LayoutTransformer/StyleTransformer.swift
Sources/RoktUXHelper/UI/Components/RowComponent.swift
Sources/RoktUXHelper/UI/Components/ScrollableRowComponent.swift
Sources/RoktUXHelper/UI/Components/StaticImageViewComponent.swift
Sources/RoktUXHelper/UI/Components/ViewModel/RowViewModel.swift
Sources/RoktUXHelper/UI/Components/ViewModel/StaticImageViewModel.swift
Sources/RoktUXHelper/Utils/Collection+Extension.swift
Tests/RoktUXHelperTests/Utils/TestCollectionExtension.swift

First of few PRs to add conditional styling to components.
This PR is to introduce `BaseStyles` that can be use instead of the individual styling properties for each component.
Subsequent PRs will include:
- consuming ConditionalStyling property
- refactoring predicate logic so that it's reusable
- updating styling according to predicate logic
Fixes [([issue](https://rokt.atlassian.net/browse/NI-460))]

NI-460 - add base style

---

CHANGELOG.md

Update changelog to reflect 0.3.1 release

NOJIRA - Update CHANGELOG.md

---

Sources/RoktUXHelper/UI/Components/DataImageCarouselComponent.swift

Need to provide the the base implementation of DataImageCarousel.
Will finalize it when the ImageCarouselIndicator is ready.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-571))]
DataImageCarouselComponent implemented
The video will be in the PR.

NI-571 Support dataImageCarousel part 1

---

Sources/RoktUXHelper/Data/Model/RoktUXCustomStateMap.swift
Sources/RoktUXHelper/Data/Model/Styles/BaseStyles.swift
Sources/RoktUXHelper/Services/LayoutState.swift
Sources/RoktUXHelper/Services/LayoutStateRepresenting.swift
Sources/RoktUXHelper/Services/LayoutTransformer/LayoutTransformer.swift
Sources/RoktUXHelper/Services/LayoutTransformer/StyleTransformer.swift
Sources/RoktUXHelper/Services/LayoutTransformer/TransformerError.swift
Sources/RoktUXHelper/UI/Components/CarouselComponent.swift
Sources/RoktUXHelper/UI/Components/DataImageCarouselComponent.swift
Sources/RoktUXHelper/UI/Components/GroupedDistributionComponent.swift
Sources/RoktUXHelper/UI/Components/ImageCarouselIndicator.swift
Sources/RoktUXHelper/UI/Components/LayoutSchemaComponent.swift
Sources/RoktUXHelper/UI/Components/OneByOneComponent.swift
Sources/RoktUXHelper/UI/Components/RowComponent.swift
Sources/RoktUXHelper/UI/Components/ScrollableColumnComponent.swift
Sources/RoktUXHelper/UI/Components/ViewModel/DataImageCarouselViewModel.swift
Sources/RoktUXHelper/UI/Components/ViewModel/ImageCarouselIndicatorViewModel.swift
Sources/RoktUXHelper/UI/Components/ViewModel/PredicateHandling.swift
Sources/RoktUXHelper/UI/Components/ViewModel/RowViewModel.swift
Sources/RoktUXHelper/UI/Components/ViewModel/ScreenSizeAdaptive.swift
Sources/RoktUXHelper/UI/Components/ViewModel/StaticImageViewModel.swift
Sources/RoktUXHelper/UI/Components/ViewModel/WhenViewModel.swift
Tests/RoktUXHelperTests/Services/LayoutTransformer/TestStyleTransformer.swift

To integrate Image carousel indicator with image carousel component.
https://github.com/user-attachments/assets/e1f5eb41-e0a7-4072-920f-ea219ba115b0
Fixes [([issue](https://rokt.atlassian.net/browse/NI-629))]

NI-629 - add indicator

---

Sources/RoktUXHelper/Data/Model/Event/RoktUXEvent.swift
Sources/RoktUXHelper/Data/Model/ExperienceResponse/CatalogItem.swift
Sources/RoktUXHelper/Data/Model/ExperienceResponse/PluginModel.swift
Sources/RoktUXHelper/Data/Model/ExperienceResponse/PluginResponse.swift
Sources/RoktUXHelper/Data/Model/ExperienceResponse/RoktUXPageModel.swift
Sources/RoktUXHelper/RoktUX.swift
Sources/RoktUXHelper/Services/Events/EventService.swift
Sources/RoktUXHelper/Services/LayoutTransformer/LayoutTransformer.swift
Sources/RoktUXHelper/Services/UXEventsDelegate.swift
Tests/RoktUXHelperTests/Services/Events/TestEventService.swift
Tests/RoktUXHelperTests/UI/Utils/MockModels.swift

Made a few properties in CatalogItems and layoutId/pluginId not optional, reflecting the schema from ecommerce API.
Fixes [([issue](https://rokt.atlassian.net/browse/NI-472))]
models updated:
- CartItemInstantPurchase
- CatalogItem
- PluginWrapperModel
- LayoutPlugin

NI-472 - make catalog item fields mandatory

---

Package.resolved
Package.swift
Sources/RoktUXHelper/Data/Model/Styles/BaseStyles.swift

- update dcui version to 2.2.0
Fixes [([issue](https://rokt.atlassian.net/browse/NI-632))]

NI-632 - update dcui 2.2.0 version

---

CHANGELOG.md

update changelog for 0.4.0

---

.github/workflows/release-from-main.yml

There were some unnecessary logic in the release process. Refactored them to make the release process more efficient

NI-795 update release from main

---

.github/pull_request_template.md
.github/workflows/draft-release.yml
CHANGELOG.md
README.md

The process of creating the release draft from the main branch needs to be updated to simplify the release process.
- The workflow updated to bump the version as major, minor, or patch based on the input provided by the user.
- The readme updated to reflect the changes in the workflow

update the Create draft release form main

---

CHANGELOG.md
Sources/RoktUXHelper/UI/Components/CarouselComponent.swift
Sources/RoktUXHelper/UI/Components/Common/View+Extension.swift
Sources/RoktUXHelper/UI/Components/GroupedDistributionComponent.swift
Sources/RoktUXHelper/UI/Components/OneByOneComponent.swift
Sources/RoktUXHelper/UI/Components/Style/StyleComponent.swift

Implement visibility checks in the offer views
Fixes [LAYOUT-2303](https://rokt.atlassian.net/browse/LAYOUT-2303)
* Introduced ComponentVisibilityInfo class to encapsulate visibility state.
* Updated the onBecomingViewed modifier to include visibility checks.
Tested in the SDK, and the signals are triggered

LAYOUT-2303 - Implement visibility checks in the offer views

---

.cortex/catalog/ios-sdk.yaml
.github/CODEOWNERS
README.md

Update ownership and team the repo 
Team update

NoJira - Update ownership and team

---

.github/workflows/draft-release.yml
.github/workflows/release-from-main.yml

Fix the draft release github action
* Remove the label in the generated PR
* Change the bump-version action to use plugin
* Refactor the release-from-main to detect changes on VERSION file

NoJira - Fix the draft release github action

---

CHANGELOG.md
Sources/RoktUXHelper/Data/Model/Constants.swift
Sources/RoktUXHelper/UI/Components/CatalogResponseButtonComponent.swift
Sources/RoktUXHelper/UI/Components/CloseButtonComponent.swift
Sources/RoktUXHelper/UI/Components/CreativeResponseComponent.swift
Sources/RoktUXHelper/UI/Components/ProgressControlComponent.swift
Sources/RoktUXHelper/UI/Components/StaticLinkComponent.swift
Sources/RoktUXHelper/UI/Components/ToggleButtonComponent.swift
Tests/RoktUXHelperTests/UI/Components/TestCloseButtonComponent.swift
Tests/RoktUXHelperTests/UI/Components/TestProgressControlComponent.swift

Add accessibility traits
Fixes SQDSDKS-7363
- Added voiceover accessibility button trait to CloseButtonComponent, CatalogResponseButtonComponent, CreativeResponseComponent, ProgressControlComponent, & ToggleButtonComponent
- Added voiceover accessibility link trait to StaticLinkComponent
N/A

feat: SQDSDKS-7363 - Add accessibility traits

---

.cursor/rules/build-and-test.mdc
.cursor/rules/code-review-architecture.mdc
.cursor/rules/project-overview.mdc

chore: Add basic cursor rules

---

.github/pull_request_template.md

Added a standardized PULL_REQUEST_TEMPLATE.md with clear sections for summary, testing, references, and checklist.
Fixes [issue](https://rokt.atlassian.net/browse/SDKE-245)
Updated the pull_request_template.md file.
Tested locally.

ci: Standardize pull request template
